
name: cd

on:
  push:
  
    tags:
   
      - 'v**'

jobs:
  aws:
    name: AWS
    runs-on: ubuntu-latest
    steps:
  - name: Check out code
    uses: actions/checkout@v2
      
  - name: Set up Docker Buildx
    uses: docker/setup-buildx-action@v1

  - name: Configure AWS Credentials using Secrets
    uses: aws-actions/configure-aws-credentials@v1
    with:

      aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
    
      aws-region: us-east-1

  - name: Login to Amazon ECR
    id: login-ecr
    uses: aws-actions/amazon-ecr-login@v1

  - name: Build and push to Amazon ECR
    env:

      ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
  
      ECR_REPO: fragments

      VERSION_TAG: ${{ github.ref_name }}
    uses: docker/build-push-action@v2
    with:
      push: true
 
      tags: ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPO }}:${{ env.VERSION_TAG }}, ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPO }}:latest
